name: 5THSEMEL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - ag-ui-protocol==0.1.9
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.11.0
      - argcomplete==3.6.3
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - boto3==1.40.55
      - botocore==1.40.55
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cohere==5.19.0
      - colorama==0.4.6
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - email-validator==2.3.0
      - eval-type-backport==0.2.2
      - executing==2.2.1
      - fastapi==0.119.1
      - fastapi-cli==0.0.14
      - fastapi-cloud-cli==0.3.1
      - fastavro==1.12.1
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - genai-prices==0.0.35
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.26.0
      - google-api-python-client==2.185.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-genai==1.45.0
      - googleapis-common-protos==1.71.0
      - greenlet==3.2.4
      - griffe==1.14.0
      - groq==0.33.0
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.35.3
      - idna==3.11
      - importlib-metadata==8.7.0
      - invoke==2.2.1
      - jinja2==3.1.6
      - jiter==0.11.1
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - logfire==4.14.0
      - logfire-api==4.14.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mcp==1.18.0
      - mdurl==0.1.2
      - mistralai==1.9.11
      - multidict==6.7.0
      - nexus-rpc==1.1.0
      - openai==2.6.0
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-http==1.38.0
      - opentelemetry-instrumentation==0.59b0
      - opentelemetry-instrumentation-httpx==0.59b0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - opentelemetry-util-http==0.59b0
      - outcome==1.3.0.post0
      - packaging==25.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.3
      - pydantic-ai==1.2.1
      - pydantic-ai-slim==1.2.1
      - pydantic-core==2.41.4
      - pydantic-evals==1.2.1
      - pydantic-graph==1.2.1
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - s3transfer==0.14.0
      - selenium==4.37.0
      - sentry-sdk==2.42.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - temporalio==1.18.0
      - tenacity==9.1.2
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - trio==0.31.0
      - trio-websocket==0.12.2
      - typer==0.20.0
      - types-protobuf==6.32.1.20250918
      - types-requests==2.32.4.20250913
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wrapt==1.17.3
      - wsproto==1.2.0
      - yarl==1.22.0
      - zipp==3.23.0

